#docker network create --driver bridge rossmann-network
#docker network inspect rossmann-network

networks:
  rossmann-network:
    external: true

services:
  users_db:
    container_name: users-db
    networks:
      - rossmann-network
    image: postgres:latest
    restart: always
    ports:
      - 4000:5432
    environment:
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
      POSTGRES_DB: ${USERS_DB_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USERS_DB_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  users_app:
    container_name: users-app
    networks:
      - rossmann-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      users_db:
        condition: service_healthy
    env_file:
      - .env